export const homeProjects = [
  {
    id: 1,
    name: "Next Ventures",
    shortDescription:
      "A platform designed for early-stage entrepreneurs to pitch, browse, and engage with startup ideas. It's built to impress both users and investors with blazing speed, compelling visuals, and a modern tech stack.",
    mainFeatures: [
      "Leveraged Partial Prerendering and After for faster loading.",
      "Simplified idea submission with a clean, intuitive design.",
      "Enhanced browsing with seamless performance optimization.",
      "Built with Next.js, React, and TypeScript for scalability.",
      "Styled using Tailwind CSS with animations by Framer Motion.",
      "Used Zustand for state management and Zod for validation.",
      "Integrated MongoDB and RESTful APIs with Node.js, Express.",
      "Designed a user-friendly interface for seamless interactions.",
    ],
    techUsed: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "TypeScript",
      "Framer Motion",
      "Sanity cms",
      "Auth.js",
      "markdown",
      "GROQ",
      "Sentry",
    ],
    image: "/amazon-clone-homepage.webp",
    className: ["lg:py-8", "lg:mt-8"],
  },
  {
    id: 2,
    name: "Zenith Minds",
    shortDescription:
      "Developed ZenithMinds, an educational platform connecting students and instructors, fostering global collaboration and continuous learning.",
    mainFeatures: [
      "Built with Next.js, React, and TypeScript for scalability.",
      "Styled using Tailwind CSS with animations by Framer Motion.",
      "Used Zustand for state management and Zod for validation.",
      "Integrated MongoDB and RESTful APIs with Node.js, Express.",
      "Designed a user-friendly interface for seamless interactions.",
    ],
    techUsed: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "TypeScript",
      "Turborepo",
      "Zod",
      "Framer Motion",
      "Zustand",
      "MongoDB",
      "NodeJS",
      "ExpressJS",
      "Razorpay",
    ],
    image: "/new-chatbot.webp",
    className: ["lg:py-8"],
  },
  {
    id: 3,
    name: "FLux Lura",
    shortDescription:
      "A free online tool for seamless multimedia conversion. Effortlessly transform images, audio, and videos with ease and elevate your content instantly!",
    mainFeatures: [
      "Developed a multimedia converter using Next.js and TypeScript.",
      "Styled with Tailwind CSS and enhanced with Framer Motion for smooth animations.",
      "Integrated Shadcn UI for consistent and accessible components.",
      "Leveraged FFmpeg for efficient media processing and conversion.",
      "Created a responsive and intuitive user interface for effortless conversions.",
    ],
    techUsed: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "TypeScript",
      "Framer Motion",
      "Shadcn",
      "FFmpeg",
    ],
    image: "/movie-homepage.webp",
  },
  {
    id: 4,
    name: "Personal Portfolio",
    shortDescription:
      "A personal portfolio showcasing modern web design and user experience with sleek layouts, smooth animations, and highlights of my skills and projects.",
    mainFeatures: [
      "Integrated PostgreSQL and Prisma for efficient data handling.",
      "Built with Next.js and TypeScript for performance and scalability.",
      "Implemented state management with Zustand and validation using Zod.",
      "Secured authentication with Auth.js for user account management.",
    ],
    techUsed: [
      "Next.js",
      "React",
      "TypeScript",
      "MDX",
      "Tailwind CSS",
      "Framer Motion",
      "Zustand",
      "Zod",
      "PostgreSQL",
      "Prisma",
      "Auth.js",
    ],
    image: "/reactjobs-homepage.webp",
  },
  {
    id: 5,
    name: "StarForge",
    shortDescription:
      "An AI SaaS landing page showcasing modern UI/UX excellence. With sleek design and smooth animations, it delivers an engaging user experience and serves as an inspiring reference for developers and designers.",
    mainFeatures: [
      "Built with React and Vite for fast and scalable development.",
      "Designed responsive layouts using Tailwind CSS.",
      "Enhanced user experience with smooth animations using react-just-parallax.",
      "Implemented JavaScript for dynamic interactions and seamless functionality.",
    ],
    techUsed: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "react-just-parallax",
      "Vercel",
    ],
    image: "/todo-app.webp",
  },
  // Add more projects as needed
];
